name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: ['1.19', '1.20']
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}
          check-latest: true
          cache: true

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: "go test -v -race -coverprofile='coverage.out' ./..."
        shell: bash

      - name: Code coverage
        run: "if [ -f coverage.out ]; then bash <(curl -s https://codecov.io/bash); fi"
        shell: bash
